export default `Africa
	Abidjan,0,GMT
	Accra,0,GMT
	Addis_Ababa,3,EAT
	Algiers,1,CET|CEST
	Asmara,3,EAT
	Bamako,0,GMT
	Bangui,1,WAT
	Banjul,0,GMT
	Bissau,0,GMT
	Blantyre,2,CAT,s
	Brazzaville,1,WAT
	Bujumbura,2,CAT,s
	Cairo,2,EET|EEST
	Casablanca,0,WET|WEST,saha
	Ceuta,1,CET|CEST,eu2
	Conakry,0,GMT
	Dakar,0,GMT
	Dar_Es_Salaam,3,EAT
	Djibouti,3,EAT
	Douala,1,WAT
	El_Aaiun,0,WET|WEST,saha
	Freetown,0,GMT
	Gaborone,2,CAT,s
	Harare,2,CAT,s
	Johannesburg,2,SAST,s
	Juba,3,CAT
	Kampala,3,EAT
	Khartoum,2,CAT
	Kigali,2,CAT,s
	Kinshasa,1,WAT
	Lagos,1,WAT
	Libreville,1,WAT
	Lome,0,GMT
	Luanda,1,WAT
	Lubumbashi,2,CAT,s
	Lusaka,2,CAT,s
	Malabo,1,WAT
	Maputo,2,CAT,s
	Maseru,2,SAST,s
	Mbabane,2,SAST,s
	Mogadishu,3,EAT
	Monrovia,0,GMT
	Nairobi,3,EAT
	Ndjamena,1,WAT
	Niamey,1,WAT
	Nouakchott,0,GMT
	Ouagadougou,0,GMT
	Porto-novo,1,WAT
	Sao_Tome,0,GMT
	Tripoli,2,EET|EEST
	Tunis,1,CET|CEST
	Windhoek,1,CAT,s
America
	Adak,-10,HST|HDT,usa
	Anchorage,-9,AKST|AKDT,usa
	Anguilla,-4,AST|ADT
	Antigua,-4,AST|ADT
	Araguaina,-3,BRT
	Argentina,-3,ART,s
	Argentina/Buenos_Aires,-3,ART,s
	Argentina/Catamarca,-3,ART,s
	Argentina/Cordoba,-3,ART,s
	Argentina/La_Rioja,-3,ART,s
	Argentina/Mendoza,-3,ART,s
	Argentina/Rio_Gallegos,-3,ART,s
	Argentina/Salta,-3,ART,s
	Argentina/San_Juan,-3,ART,s
	Argentina/San_Luis,-3,ART,s
	Argentina/Tucuman,-3,ART,s
	Argentina/Ushuaia,-3,ART,s
	Aruba,-4,AST|ADT
	Asuncion,-4,PYT|PYST,par,s
	Atikokan,-5,EST|EDT
	Bahia,-3,BRT
	Bahia_Banderas,-6,CST|CDT,mex
	Barbados,-4,AST|ADT
	Belem,-3,BRT
	Belize,-6,CST|CDT
	Blanc-sablon,-4,AST|ADT
	Boa_Vista,-4,AMT
	Bogota,-5,COT
	Boise,-7,MST|MDT,usa
	Buenos_Aires,-3,ART,s
	Cambridge_Bay,-7,MST|MDT,usa
	Campo_Grande,-4,AMT,s
	Cancun,-5,EST|EDT
	Caracas,-4,VET
	Catamarca,-3,ART,s
	Cayenne,-3,GFT
	Cayman,-5,EST|EDT
	Chicago,-6,CST|CDT,usa
	Chihuahua,-7,HNPMX|HEPMX,mex
	Cordoba,-3,ART,s
	Costa_Rica,-6,CST|CDT
	Creston,-7,MST|MDT
	Cuiaba,-4,AMT,s
	Curacao,-4,AST|ADT
	Danmarkshavn,0,GMT
	Dawson,-7,MST|MDT
	Dawson_Creek,-7,MST|MDT
	Denver,-7,MST|MDT,usa
	Detroit,-5,EST|EDT,usa
	Dominica,-4,AST|ADT
	Edmonton,-7,MST|MDT,usa
	Eirunepe,-5,ACT
	El_Salvador,-6,CST|CDT
	Ensenada,-8,PST|PDT,usa
	Fort_Nelson,-7,MST|MDT
	Fort_wayne,-5,EST|EDT,usa
	Fortaleza,-3,BRT,s
	Glace_Bay,-4,AST|ADT,usa
	Godthab,-3,WGT|WGST,green
	Goose_Bay,-4,AST|ADT,usa
	Grand_Turk,-5,EST|EDT,usa
	Grenada,-4,AST|ADT
	Guadeloupe,-4,AST|ADT
	Guatemala,-6,CST|CDT
	Guayaquil,-5,ECT
	Guyana,-4,GYT
	Halifax,-4,AST|ADT,usa
	Havana,-5,HNCU|HECU,cuba
	Hermosillo,-7,HNPMX|HEPMX
	Indiana,-5,EST|EDT,usa
	Indiana/Indianapolis,-5,EST|EDT,usa
	Indiana/Knox,-6,CST|CDT,usa
	Indiana/Marengo,-5,EST|EDT,usa
	Indiana/Petersburg,-5,EST|EDT,usa
	Indiana/Tell_City,-6,CST|CDT,usa
	Indiana/Vevay,-5,EST|EDT,usa
	Indiana/Vincennes,-5,EST|EDT,usa
	Indiana/Winamac,-5,EST|EDT,usa
	Indianapolis,-5,EST|EDT,usa
	Inuvik,-7,MST|MDT,usa
	Iqaluit,-5,EST|EDT,usa
	Jamaica,-5,EST|EDT
	Jujuy,-3,ART,s
	Juneau,-9,AKST|AKDT,usa
	Kentucky,-5,EST|EDT,usa
	Kentucky/Louisville,-5,EST|EDT,usa
	Kentucky/Petersburg,-5,EST|EDT,usa
	Knox_in,-5,EST|EDT,usa
	Kralendijk,-4,AST|ADT
	La_Paz,-4,BOT,s
	Lima,-5,PET,s
	Los_Angeles,-8,PST|PDT,usa
	Louisville,-5,EST|EDT,usa
	Lower_Princes,-4,AST|ADT
	Maceio,-3,BRT
	Managua,-6,CST|CDT
	Manaus,-4,AMT,s
	Marigot,-4,AST|ADT
	Martinique,-4,AST|ADT
	Matamoros,-6,CST|CDT,usa
	Mazatlan,-7,HNPMX|HEPMX,mex
	Mendoza,-3,ART,s
	Menominee,-6,CST|CDT,usa
	Merida,-6,CST|CDT,mex
	Metlakatla,-9,AKST|AKDT,usa
	Mexico_City,-6,CST|CDT,mex
	Miquelon,-3,HNPM|HEPM,usa
	Moncton,-4,AST|ADT,usa
	Monterrey,-6,CST|CDT,mex
	Montevideo,-3,UYT,s
	Montreal,-5,EST|EDT,usa
	Montserrat,-4,AST|ADT
	Nassau,-5,EST|EDT,usa
	New_York,-5,EST|EDT,usa
	Nipigon,-5,EST|EDT,usa
	Nome,-9,AKST|AKDT,usa
	Noronha,-2,FNT
	North_Dakota/Beulah,-6,CST|CDT,usa
	North_Dakota/Center,-6,CST|CDT,usa
	North_Dakota/New_Salem,-6,CST|CDT,usa
	North_dakota,-7,MST|MDT,usa
	Nuuk,-3,WGT|WGST,green
	Ojinaga,-7,MST|MDT,usa
	Panama,-5,EST|EDT
	Pangnirtung,-5,EST|EDT,usa
	Paramaribo,-3,SRT
	Phoenix,-7,MST|MDT
	Port-au-prince,-5,EST|EDT,usa
	Port_Of_Spain,-4,AST|ADT
	Porto_Velho,-4,AMT
	Porto_acre,-5,ACT,s
	Puerto_Rico,-4,AST|ADT
	Punta_Arenas,-3,CLT|CLST,s
	Rainy_River,-6,CST|CDT,usa
	Rankin_Inlet,-6,CST|CDT,usa
	Recife,-3,BRT
	Regina,-6,CST|CDT
	Resolute,-6,CST|CDT,usa
	Rio_Branco,-5,ACT,s
	Rosario,-3,ART,s
	Santa_isabel,-8,PST|PDT,usa
	Santarem,-3,BRT
	Santiago,-4,CLT|CLST,chile,s
	Santo_Domingo,-4,AST|ADT
	Sao_Paulo,-3,BRT,s
	Scoresbysund,-1,HNEG|HEEG,eu0
	Shiprock,-7,MST|MDT,usa
	Sitka,-9,AKST|AKDT,usa
	St_Barthelemy,-4,AST|ADT
	St_Johns,-3.5,HNTN|HETN,usa
	St_Kitts,-4,AST|ADT
	St_Lucia,-4,AST|ADT
	St_Thomas,-4,AST|ADT
	St_Vincent,-4,AST|ADT
	Swift_Current,-6,CST|CDT
	Tegucigalpa,-6,CST|CDT
	Thule,-4,AST|ADT,usa
	Thunder_Bay,-5,EST|EDT,usa
	Tijuana,-8,PST|PDT,usa
	Toronto,-5,EST|EDT,usa
	Tortola,-4,AST|ADT
	Vancouver,-8,PST|PDT,usa
	Virgin,-4,AST|ADT
	Whitehorse,-7,MST|MDT
	Winnipeg,-6,CST|CDT,usa
	Yakutat,-9,AKST|AKDT,usa
	Yellowknife,-7,MST|MDT,usa
Antarctica
	Casey,8,CAST|CAST,ant,s
	Davis,7,DAVT,s
	Dumontdurville,10,PGT,s
	Macquarie,11,AEST|AEDT,aus,s
	Mawson,5,MAWT,s
	Mcmurdo,12,NZST|NZDT,nz,s
	Palmer,-3,ART,s
	Rothera,-3,ART,s
	South_pole,12,NZST|NZDT,nz,s
	Syowa,3,AST
	Troll,2,GMT,troll,s
	Vostok,6,MSK+4,s
Arctic
	Longyearbyen,1,CET|CEST,eu2
Asia
	Aden,3,AST
	Almaty,6,ALMT
	Amman,2,EET|EEST,jord
	Anadyr,12,ANAT
	Aqtau,5,ALMT
	Aqtobe,5,ALMT
	Ashgabat,5,TMT
	Ashkhabad,5,TMT
	Atyrau,5,ALMT
	Baghdad,3,AST
	Bahrain,3,AST
	Baku,4,AZT
	Bangkok,7,ICT
	Barnaul,7,KRAT
	Beirut,2,EET|EEST,leb
	Bishkek,6,KGT
	Brunei,8,BNT
	Calcutta,5.5,IST
	Chita,9,YAKT
	Choibalsan,8,ULAT
	Chongqing,8,CST
	Chungking,8,CST
	Colombo,5.5,IST
	Dacca,6,BST
	Damascus,2,EET|EEST,syr
	Dhaka,6,BST
	Dili,9,TLT,s
	Dubai,4,GST
	Dushanbe,5,TJT
	Famagusta,2,EET|EEST,eu3
	Gaza,2,EET|EEST,pal
	Harbin,8,CST
	Hebron,2,EET|EEST,pal
	Ho_Chi_Minh,7,ICT
	Hong_Kong,8,HKT
	Hovd,7,HOVT
	Irkutsk,8,IRKT
	Istanbul,3,TRT
	Jakarta,7,WIB,s
	Jayapura,9,WIT,s
	Jerusalem,2,IST|IDT,isr
	Kabul,4.5,AFT
	Kamchatka,12,PETT
	Karachi,5,PKT
	Kashgar,8,CST
	Kathmandu,5.75,NPT
	Katmandu,5.75,NPT
	Khandyga,9,YAKT
	Kolkata,5.5,IST
	Krasnoyarsk,7,KRAT
	Kuala_Lumpur,8,MYT,s
	Kuching,8,MYT
	Kuwait,3,AST
	Macao,8,CST
	Macau,8,CST
	Magadan,11,MAGT
	Makassar,8,WITA,s
	Manila,8,PHST
	Muscat,4,GST
	Nicosia,2,EET|EEST,eu3
	Novokuznetsk,7,KRAT
	Novosibirsk,7,NOVT
	Omsk,6,OMST
	Oral,5,ALMT
	Phnom_Penh,7,ICT
	Pontianak,7,WIB
	Pyongyang,9,KST
	Qatar,3,AST
	Qostanay,6,ALMT
	Qyzylorda,6,ALMT
	Rangoon,6.5,MMT
	Riyadh,3,AST
	Saigon,7,ICT
	Sakhalin,11,SAKT
	Samarkand,5,UZT
	Seoul,9,KST
	Shanghai,8,CST
	Singapore,8,SGT,s
	Srednekolymsk,12,SRET
	Taipei,8,CST
	Tashkent,5,UZT
	Tbilisi,4,GET
	Tehran,3.5,IRST|IRDT,iran
	Tel_aviv,2,IST|IDT,isr
	Thimbu,6,BT
	Thimphu,6,BT
	Tokyo,9,JST
	Tomsk,7,OMST
	Ujung_pandang,8,WITA,s
	Ulaanbaatar,8,ULAT
	Ulan_bator,8,ULAT
	Urumqi,8,CST
	Ust-nera,10,VLAT
	Vientiane,7,ICT
	Vladivostok,10,VLAT
	Yakutsk,10,YAKT
	Yangon,6.5,MMT
	Yekaterinburg,5,YEKT
	Yerevan,4,AMT
Atlantic
	Azores,-1,AZOT|AZOST,eu0
	Bermuda,-4,AST|ADT,usa
	Canary,0,WET|WEST,eu1
	Cape_Verde,-1,CVT
	Faeroe,0,WET|WEST,eu1
	Faroe,0,WET|WEST,eu1
	Jan_mayen,1,CET|CEST,eu2
	Madeira,0,WET|WEST,eu1
	Reykjavik,0,GMT
	South_Georgia,-2,GST
	St_Helena,0,GMT
	Stanley,-3,FKST,s
Australia
	Act,10,AEST|AEDT,aus,s
	Adelaide,9.5,ACST|ACDT,aus,s
	Brisbane,10,AEST,s
	Broken_Hill,9.5,ACST|ACDT,aus,s
	Canberra,10,AEST|AEDT,aus,s
	Currie,10,AEST|AEDT,aus,s
	Darwin,9.5,ACST,s
	Eucla,8.75,ACWST,s
	Hobart,10,AEST|AEDT,aus,s
	Lhi,10.5,LHST|LHDT,lhow,s
	Lindeman,10,AEST,s
	Lord_Howe,10.5,LHST|LHDT,lhow,s
	Melbourne,10,AEST|AEDT,aus,s
	North,9.5,ACST,s
	Nsw,10,AEST|AEDT,aus,s
	Perth,8,AWST,s
	Queensland,10,AEST,s
	South,9.5,ACST|ACDT,aus,s
	Sydney,10,AEST|AEDT,aus,s
	Tasmania,10,AEST|AEDT,aus,s
	Victoria,10,AEST|AEDT,aus,s
	West,8,AWST,s
	Yancowinna,9.5,ACST|ACDT,aus,s
Brazil
	Acre,-5,ACT,s
	Denoronha,-2,FNT
	East,-3,BRT,s
	West,-4,AMT,s
Canada
	Atlantic,-4,AST|ADT,usa
	Central,-6,CST|CDT,usa
	East-saskatchewan,-6,CST|CDT
	Eastern,-5,EST|EDT,usa
	Mountain,-7,MST|MDT,usa
	Newfoundland,-3.5,HNTN|HETN,usa
	Pacific,-8,PST|PDT,usa
	Saskatchewan,-6,CST|CDT
	Yukon,-7,MST|MDT
Chile
	Continental,-4,CLT|CLST,chile,s
	Easterisland,-6,EAST|EASST,east,s
Cuba
	,-5,HNCU|HECU,cuba
Egypt
	,2,EET|EEST
Eire
	,0,GMT|IST,eu1
Etc
	GMT,0,GMT
	Greenwich,0,GMT
	Uct,0,UTC
	Universal,0,UTC
	Unknown,0,UTC
	Utc,0,UTC
	Zulu,0,UTC
Europe
	Amsterdam,1,CET|CEST,eu2
	Andorra,1,CET|CEST,eu2
	Astrakhan,4,MSK
	Athens,2,EET|EEST,eu3
	Belfast,0,GMT|BST,eu1
	Belgrade,1,CET|CEST,eu2
	Berlin,1,CET|CEST,eu2
	Bratislava,1,CET|CEST,eu2
	Brussels,1,CET|CEST,eu2
	Bucharest,2,EET|EEST,eu3
	Budapest,1,CET|CEST,eu2
	Busingen,1,CET|CEST,eu2
	Chisinau,2,EET|EEST,eu2
	Copenhagen,1,CET|CEST,eu2
	Dublin,0,GMT|IST,eu1
	Gibraltar,1,CET|CEST,eu2
	Guernsey,0,GMT|BST,eu1
	Helsinki,2,EET|EEST,eu3
	Isle_Of_Man,0,GMT|BST,eu1
	Istanbul,3,TRT
	Jersey,0,GMT|BST,eu1
	Kaliningrad,2,EET|EEST
	Kiev,2,EET|EEST,eu3
	Kirov,3,MSK
	Kyiv,2,EET|EEST,eu3
	Lisbon,0,WET|WEST,eu1
	Ljubljana,1,CET|CEST,eu2
	London,0,GMT|BST,eu1
	Luxembourg,1,CET|CEST,eu2
	Madrid,1,CET|CEST,eu2
	Malta,1,CET|CEST,eu2
	Mariehamn,2,EET|EEST,eu3
	Minsk,3,MSK
	Monaco,1,CET|CEST,eu2
	Moscow,3,MSK
	Nicosia,2,EET|EEST,eu3
	Oslo,1,CET|CEST,eu2
	Paris,1,CET|CEST,eu2
	Podgorica,1,CET|CEST,eu2
	Prague,1,CET|CEST,eu2
	Riga,2,EET|EEST,eu3
	Rome,1,CET|CEST,eu2
	Samara,4,SAMT
	San_Marino,1,CET|CEST,eu2
	Sarajevo,1,CET|CEST,eu2
	Saratov,4,SAMT
	Simferopol,2,EET|EEST,eu3
	Skopje,1,CET|CEST,eu2
	Sofia,2,EET|EEST,eu3
	Stockholm,1,CET|CEST,eu2
	Tallinn,2,EET|EEST,eu3
	Tirane,1,CET|CEST,eu2
	Tiraspol,2,EET|EEST,eu2
	Ulyanovsk,4,MSK
	Uzhgorod,2,EET|EEST,eu3
	Vaduz,1,CET|CEST,eu2
	Vatican,1,CET|CEST,eu2
	Vienna,1,CET|CEST,eu2
	Vilnius,2,EET|EEST,eu3
	Volgograd,4,MSK
	Warsaw,1,CET|CEST,eu2
	Zagreb,1,CET|CEST,eu2
	Zaporozhye,2,EET|EEST,eu3
	Zurich,1,CET|CEST,eu2
GB
	,0,GMT|BST,eu1
Gb-eire
	,0,GMT|BST,eu1
Gmt+0
	,0,GMT
Gmt-0
	,0,GMT
Gmt0
	,0,GMT
Greenwich
	,0,GMT
Hongkong
	,8,HKT
Iceland
	,0,GMT
Indian
	Antananarivo,3,EAT
	Chagos,6,IOT
	Christmas,7,CXT,s
	Cocos,6.5,CCT
	Comoro,3,EAT
	Kerguelen,5,TFT,s
	Mahe,4,SCT
	Maldives,5,MVT
	Mauritius,4,MUT
	Mayotte,3,EAT
	Reunion,4,RET,s
Iran
	,3.5,IRST|IRDT,iran
Israel
	,2,IST|IDT,isr
Jamaica
	,-5,EST|EDT
Japan
	,9,JST
Kwajalein
	,12,MHT
Libya
	,2,EET|EEST
Mexico
	Bajanorte,-8,PST|PDT,usa
	Bajasur,-7,HNPMX|HEPMX,mex
	General,-6,CST|CDT,mex
Navajo
	,-7,MST|MDT,usa
Nz
	,12,NZST|NZDT,nz,s
Nz-chat
	,12.75,CHAST|CHADT,chat,s
Pacific
	Apia,13,WST|WST,s
	Auckland,12,NZST|NZDT,nz,s
	Bougainville,11,PGT,s
	Chatham,12.75,CHAST|CHADT,chat,s
	Chuuk,10,CHUT
	Easter,-6,EAST|EASST,east,s
	Efate,11,VUT
	Fakaofo,13,TKT
	Fiji,12,FJT|FJT,fiji,s
	Funafuti,12,TVT
	Galapagos,-6,COT
	Gambier,-9,GAMT
	Guadalcanal,11,SBT
	Guam,10,ChST
	Honolulu,-10,HAST|HADT
	Johnston,-10,HAST|HADT
	Kanton,13,PHOT
	Kiritimati,14,LINT
	Kosrae,11,KOST
	Kwajalein,12,MHT
	Majuro,12,MHT
	Marquesas,-9.5,MART
	Midway,-11,SST
	Nauru,12,NRT
	Niue,-11,NUT
	Norfolk,10.5,NFT|NFDT,aus
	Noumea,11,NCT
	Pago_Pago,-11,SST
	Palau,9,PWT
	Pitcairn,-8,PST
	Pohnpei,11,PONT
	Ponape,11,PONT
	Port_Moresby,10,PGT,s
	Rarotonga,-10,CKT
	Saipan,10,ChST
	Samoa,-11,SST
	Tahiti,-10,TAHT
	Tarawa,12,GILT
	Tongatapu,13,TOT,s
	Truk,10,CHUT
	Wake,12,WAKT
	Wallis,12,WFT
	Yap,10,CHUT
Poland
	,1,CET|CEST,eu2
Portugal
	,0,WET|WEST,eu1
Prc
	,8,CST
Roc
	,8,CST
Rok
	,9,KST
Singapore
	,8,SGT,s
Turkey
	,3,TRT
UTC
	,0,UTC
	Unknown,0,UTC
Uct
	,0,UTC
Universal
	,0,UTC
Us
	Alaska,-9,AKST|AKDT,usa
	Aleutian,-10,HST|HDT,usa
	Arizona,-7,MST|MDT
	Central,-6,CST|CDT,usa
	East-indiana,-5,EST|EDT,usa
	Eastern,-5,EST|EDT,usa
	Hawaii,-10,HAST|HADT
	Indiana-starke,-5,EST|EDT,usa
	Michigan,-5,EST|EDT,usa
	Mountain,-7,MST|MDT,usa
	Pacific,-8,PST|PDT,usa
	Pacific-new,-8,PST|PDT,usa
	Samoa,-11,SST
W-su
	,3,MSK
Zulu
	,0,UTC
america
	argentina/buenos_aires,-3,ART,s
	argentina/catamarca,-3,ART,s
	argentina/comodrivadavia,-3,ART,s
	argentina/cordoba,-3,ART,s
	argentina/jujuy,-3,ART,s
	argentina/mendoza,-3,ART,s
	argentina/rosario,-3,ART,s
`