// IANA codes linked to, or replaced by another one
// https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones
export default {
  "Africa/Accra": "Africa/Abidjan",
  "Africa/Addis_Ababa": "Africa/Nairobi",
  "Africa/Asmara": "Africa/Nairobi",
  "Africa/Bamako": "Africa/Abidjan",
  "Africa/Bangui": "Africa/Lagos",
  "Africa/Banjul": "Africa/Abidjan",
  "Africa/Blantyre": "Africa/Maputo",
  "Africa/Brazzaville": "Africa/Lagos",
  "Africa/Bujumbura": "Africa/Maputo",
  "Africa/Conakry": "Africa/Abidjan",
  "Africa/Dakar": "Africa/Abidjan",
  "Africa/Dar_Es_Salaam": "Africa/Nairobi",
  "Africa/Djibouti": "Africa/Nairobi",
  "Africa/Douala": "Africa/Lagos",
  "Africa/Freetown": "Africa/Abidjan",
  "Africa/Gaborone": "Africa/Maputo",
  "Africa/Harare": "Africa/Maputo",
  "Africa/Kampala": "Africa/Nairobi",
  "Africa/Kigali": "Africa/Maputo",
  "Africa/Kinshasa": "Africa/Lagos",
  "Africa/Libreville": "Africa/Lagos",
  "Africa/Lome": "Africa/Abidjan",
  "Africa/Luanda": "Africa/Lagos",
  "Africa/Lubumbashi": "Africa/Maputo",
  "Africa/Lusaka": "Africa/Maputo",
  "Africa/Malabo": "Africa/Lagos",
  "Africa/Maseru": "Africa/Johannesburg",
  "Africa/Mbabane": "Africa/Johannesburg",
  "Africa/Mogadishu": "Africa/Nairobi",
  "Africa/Niamey": "Africa/Lagos",
  "Africa/Nouakchott": "Africa/Abidjan",
  "Africa/Ouagadougou": "Africa/Abidjan",
  "Africa/Porto-novo": "Africa/Lagos",
  "America/Anguilla": "America/Puerto_Rico",
  "America/Antigua": "America/Puerto_Rico",
  // argentina
  "America/Argentina": "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca": "America/Argentina/Buenos_Aires",
  "America/Argentina/Cordoba": "America/Argentina/Buenos_Aires",
  "America/Argentina/La_Rioja": "America/Argentina/Buenos_Aires",
  "America/Argentina/Mendoza": "America/Argentina/Buenos_Aires",
  "America/Argentina/Rio_Gallegos": "America/Argentina/Buenos_Aires",
  "America/Argentina/Salta": "America/Argentina/Buenos_Aires",
  "America/Argentina/San_Juan": "America/Argentina/Buenos_Aires",
  "America/Argentina/San_Luis": "America/Argentina/Buenos_Aires",
  "America/Argentina/Tucuman": "America/Argentina/Buenos_Aires",
  "America/Argentina/Ushuaia": "America/Argentina/Buenos_Aires",
  "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
  "America/Catamarca": "America/Argentina/Buenos_Aires",
  "America/Cordoba": "America/Argentina/Buenos_Aires",
  "America/Jujuy": "America/Argentina/Buenos_Aires",
  "America/Mendoza": "America/Argentina/Buenos_Aires",

  "America/Aruba": "America/Puerto_Rico",
  "America/Blanc-sablon": "America/Puerto_Rico",
  "America/Cayman": "America/Panama",
  "America/Atikokan": "America/Panama",
  "America/Creston": "America/Phoenix",
  "America/Curacao": "America/Puerto_Rico",
  "America/Dominica": "America/Puerto_Rico",
  "America/Grenada": "America/Puerto_Rico",
  "America/Guadeloupe": "America/Puerto_Rico",
  "America/Indianapolis": "America/Indiana/Indianapolis",
  "America/Kralendijk": "America/Puerto_Rico",
  "America/Louisville": "America/Kentucky/Louisville",
  "America/Lower_Princes": "America/Puerto_Rico",
  "America/Marigot": "America/Puerto_Rico",
  "America/Montserrat": "America/Puerto_Rico",
  "America/Nassau": "America/Toronto",
  "America/Port_Of_Spain": "America/Puerto_Rico",
  "America/St_Barthelemy": "America/Puerto_Rico",
  "America/St_Kitts": "America/Puerto_Rico",
  "America/St_Lucia": "America/Puerto_Rico",
  "America/St_Thomas": "America/Puerto_Rico",
  "America/St_Vincent": "America/Puerto_Rico",
  "America/Tortola": "America/Puerto_Rico",
  "Antarctica/Dumontdurville": "Pacific/Port_Moresby",
  "Antarctica/Mcmurdo": "Pacific/Auckland",
  "Antarctica/Palmer": "Antarctica/Rothera",
  "Antarctica/Syowa": "Asia/Riyadh",
  "Arctic/Longyearbyen": "Europe/Oslo",
  "Asia/Aden": "Asia/Riyadh",
  "Asia/Bahrain": "Asia/Qatar",
  "Asia/Kuwait": "Asia/Riyadh",
  "Asia/Muscat": "Asia/Dubai",
  "Asia/Phnom_Penh": "Asia/Bangkok",
  "Asia/Urumqi": "Asia/Shanghai",
  "Asia/Vientiane": "Asia/Bangkok",
  "Atlantic/St_Helena": "Africa/Abidjan",
  "Europe/Berlin": "Europe/Busingen",
  "Europe/Bratislava": "Europe/Prague",
  "Europe/Guernsey": "Europe/London",
  "Europe/Isle_Of_Man": "Europe/London",
  "Europe/Jersey": "Europe/London",
  "Europe/Ljubljana": "Europe/Belgrade",
  "Europe/Mariehamn": "Europe/Helsinki",
  "Europe/Podgorica": "Europe/Belgrade",
  "Europe/San_Marino": "Europe/Rome",
  "Europe/Sarajevo": "Europe/Belgrade",
  "Europe/Simferopol": "Europe/Kiev",
  "Europe/Skopje": "Europe/Belgrade",
  "Europe/Vaduz": "Europe/Zurich",
  "Europe/Vatican": "Europe/Rome",
  "Europe/Zagreb": "Europe/Belgrade",
  "Indian/Antananarivo": "Africa/Nairobi",
  "Indian/Comoro": "Africa/Nairobi",
  "Indian/Mayotte": "Africa/Nairobi",
  "Pacific/Midway": "Pacific/Pago_Pago",
  "Pacific/Saipan": "Pacific/Guam",
  // Intl.DateTimeFormat() can return this
  "UTC/Unknown": "Etc/Utc",

  // 'america/argentina/comodrivadavia': 'America/Catamarca',
  // 'america/argentina/buenos_aires': 'America/Buenos_aires',
  // 'america/argentina/catamarca': 'America/Catamarca',
  // 'america/argentina/cordoba': 'America/Cordoba',
  // 'america/argentina/jujuy': 'America/Jujuy',
  // 'america/argentina/mendoza': 'America/Mendoza',
  // 'america/argentina/rosario': 'America/Cordoba',

  // 'america/ensenada': 'America/Tijuana',
  // 'america/fort_wayne': 'America/Indianapolis',
  // 'america/godthab': 'America/Nuuk',
  // 'america/indiana': 'America/Indianapolis',
  // 'america/indiana/indianapolis': 'America/Indianapolis',
  // 'america/kentucky': 'America/Louisville',
  // 'america/kentucky/louisville': 'America/Louisville',
  // 'america/north_dakota': 'America/Boise',
  // 'america/knox_in': 'America/Indiana/knox',
  // 'america/montreal': 'America/Toronto',
  // 'america/porto_acre': 'America/Rio_branco',
  // 'america/rosario': 'America/Cordoba',
  // 'america/santa_isabel': 'America/Tijuana',
  // 'america/shiprock': 'America/Denver',
  // 'america/virgin': 'America/Port_of_spain',
  // 'antarctica/south_pole': 'Pacific/Auckland',
  // 'asia/ashkhabad': 'Asia/Ashgabat',
  // 'asia/calcutta': 'Asia/Kolkata',
  // 'asia/chongqing': 'Asia/Shanghai',
  // 'asia/chungking': 'Asia/Shanghai',
  // 'asia/dacca': 'Asia/Dhaka',
  // 'asia/harbin': 'Asia/Shanghai',
  // 'asia/istanbul': 'Europe/Istanbul',
  // 'asia/kashgar': 'Asia/Urumqi',
  // 'asia/katmandu': 'Asia/Kathmandu',
  // 'asia/macao': 'Asia/Macau',
  // 'asia/rangoon': 'Asia/Yangon',
  // 'asia/saigon': 'Asia/Ho_chi_minh',
  // 'asia/tel_aviv': 'Asia/Jerusalem',
  // 'asia/thimbu': 'Asia/Thimphu',
  // 'asia/ujung_pandang': 'Asia/Makassar',
  // 'asia/ulan_bator': 'Asia/Ulaanbaatar',
  // 'atlantic/faeroe': 'Atlantic/Faroe',
  // 'atlantic/jan_mayen': 'Europe/Oslo',
  // 'australia/act': 'Australia/Sydney',
  // 'australia/canberra': 'Australia/Sydney',
  // 'australia/currie': 'Australia/Hobart',
  // 'australia/lhi': 'Australia/Lord_howe',
  // 'australia/north': 'Australia/Darwin',
  // 'australia/nsw': 'Australia/Sydney',
  // 'australia/queensland': 'Australia/Brisbane',
  // 'australia/south': 'Australia/Adelaide',
  // 'australia/tasmania': 'Australia/Hobart',
  // 'australia/victoria': 'Australia/Melbourne',
  // 'australia/west': 'Australia/Perth',
  // 'australia/yancowinna': 'Australia/Broken_hill',
  // 'brazil/acre': 'America/Rio_branco',
  // 'brazil/denoronha': 'America/Noronha',
  // 'brazil/east': 'America/Sao_paulo',
  // 'brazil/west': 'America/Manaus',
  // 'canada/atlantic': 'America/Halifax',
  // 'canada/central': 'America/Winnipeg',
  // 'canada/east-saskatchewan': 'America/Regina',
  // 'canada/eastern': 'America/Toronto',
  // 'canada/mountain': 'America/Edmonton',
  // 'canada/newfoundland': 'America/St_johns',
  // 'canada/pacific': 'America/Vancouver',
  // 'canada/saskatchewan': 'America/Regina',
  // 'canada/yukon': 'America/Whitehorse',
  // 'chile/continental': 'America/Santiago',
  // 'chile/easterisland': 'Pacific/Easter',
  // 'cuba': 'America/Havana',
  // 'egypt': 'Africa/Cairo',
  // 'eire': 'Europe/Dublin',
  // 'etc/greenwich': 'Etc/Gmt',
  // 'etc/uct': 'Etc/Utc',
  // 'etc/universal': 'Etc/Utc',
  // 'etc/zulu': 'Etc/Utc',
  // 'europe/belfast': 'Europe/London',
  // 'europe/nicosia': 'Asia/Nicosia',
  // 'europe/tiraspol': 'Europe/Chisinau',
  // 'gb-eire': 'Europe/London',
  // 'gb': 'Europe/London',
  // 'gmt-0': 'Etc/Gmt',
  // 'gmt+0': 'Etc/Gmt',
  // 'gmt0': 'Etc/Gmt',
  // 'greenwich': 'Etc/Gmt',
  // 'hongkong': 'Asia/Hong_kong',
  // 'iceland': 'Atlantic/Reykjavik',
  // 'iran': 'Asia/Tehran',
  // 'israel': 'Asia/Jerusalem',
  // 'jamaica': 'America/Jamaica',
  // 'japan': 'Asia/Tokyo',
  // 'kwajalein': 'Pacific/Kwajalein',
  // 'libya': 'Africa/Tripoli',
  // 'mexico/bajanorte': 'America/Tijuana',
  // 'mexico/bajasur': 'America/Mazatlan',
  // 'mexico/general': 'America/Mexico_city',
  // 'navajo': 'America/Denver',
  // 'nz-chat': 'Pacific/Chatham',
  // 'nz': 'Pacific/Auckland',
  // 'pacific/johnston': 'Pacific/Honolulu',
  // 'pacific/ponape': 'Pacific/Pohnpei',
  // 'pacific/samoa': 'Pacific/Pago_pago',
  // 'pacific/truk': 'Pacific/Chuuk',
  // 'pacific/yap': 'Pacific/Chuuk',
  // 'poland': 'Europe/Warsaw',
  // 'portugal': 'Europe/Lisbon',
  // 'prc': 'Asia/Shanghai',
  // 'roc': 'Asia/Taipei',
  // 'rok': 'Asia/Seoul',
  // 'singapore': 'Asia/Singapore',
  // 'turkey': 'Europe/Istanbul',
  // 'uct': 'Etc/Utc',
  // 'universal': 'Etc/Utc',
  // 'us/alaska': 'America/Anchorage',
  // 'us/aleutian': 'America/Adak',
  // 'us/arizona': 'America/Phoenix',
  // 'us/central': 'America/Chicago',
  // 'us/east-indiana': 'America/Indianapolis',
  // 'us/eastern': 'America/New_york',
  // 'us/hawaii': 'Pacific/Honolulu',
  // 'us/indiana-starke': 'America/Indiana/knox',
  // 'us/michigan': 'America/Detroit',
  // 'us/mountain': 'America/Denver',
  // 'us/pacific-new': 'America/Los_angeles',
  // 'us/pacific': 'America/Los_angeles',
  // 'us/samoa': 'Pacific/Pago_pago',
  // 'utc': 'Etc/Utc',
  // 'w-su': 'Europe/Moscow',
  // 'zulu': 'Etc/Utc',
  // 'etc/unknown': 'Etc/Utc',
  // 'europe/kiev': 'Europe/Kyiv',

}
