// dupes:
// CST|CDT
// WET|WEST
// ALMT
// GMT
// AMT
// CST
// GST
export default {
  'Africa/Abidjan': ['GMT'],
  'Africa/Algiers': ['CET', 'CEST'],
  'Africa/Bissau': ['GMT'],
  'Africa/Cairo': ['EET', 'EEST'],
  'Africa/Casablanca': ['WET', 'WEST'],
  'Africa/Ceuta': ['CET', 'CEST'],
  'Africa/El_Aaiun': ['WET', 'WEST'],
  'Africa/Johannesburg': ['SAST'],
  'Africa/Juba': ['CAT'],
  'Africa/Khartoum': ['CAT'],
  'Africa/Lagos': ['WAT'],
  'Africa/Maputo': ['CAT'],
  'Africa/Monrovia': ['GMT'],
  'Africa/Nairobi': ['EAT'],
  'Africa/Ndjamena': ['WAT'],
  'Africa/Sao_Tome': ['GMT'],
  'Africa/Tripoli': ['EET', 'EEST'],
  'Africa/Tunis': ['CET', 'CEST'],
  'Africa/Windhoek': ['CAT'],
  'America/Adak': ['HST', 'HDT'],
  'America/Anchorage': ['AKST', 'AKDT'],
  'America/Araguaina': ['BRT'],
  'America/Argentina/Buenos_Aires': ['ART'],
  'America/Argentina/Catamarca': ['ART'],
  'America/Argentina/Cordoba': ['ART'],
  'America/Argentina/Jujuy': ['ART'],
  'America/Argentina/La_Rioja': ['ART'],
  'America/Argentina/Mendoza': ['ART'],
  'America/Argentina/Rio_Gallegos': ['ART'],
  'America/Argentina/Salta': ['ART'],
  'America/Argentina/San_Juan': ['ART'],
  'America/Argentina/San_Luis': ['ART'],
  'America/Argentina/Tucuman': ['ART'],
  'America/Argentina/Ushuaia': ['ART'],
  'America/Asuncion': ['PYT', 'PYST'],
  'America/Bahia': ['BRT'],
  'America/Bahia_Banderas': ['CST', 'CDT'],
  'America/Barbados': ['AST', 'ADT'],
  'America/Belem': ['BRT'],
  'America/Belize': ['CST', 'CDT'],
  'America/Boa_Vista': ['AMT'],
  'America/Bogota': ['COT'],
  'America/Boise': ['MST', 'MDT'],
  'America/Cambridge_Bay': ['MST', 'MDT'],
  'America/Campo_Grande': ['AMT'],
  'America/Cancun': ['EST', 'EDT'],
  'America/Caracas': ['VET'],
  'America/Cayenne': ['GFT'],
  'America/Chicago': ['CST', 'CDT'],
  'America/Chihuahua': ['HNPMX', 'HEPMX'],
  'America/Costa_Rica': ['CST', 'CDT'],
  'America/Cuiaba': ['AMT'],
  'America/Danmarkshavn': ['GMT'],
  'America/Dawson': ['MST', 'MDT'],
  'America/Dawson_Creek': ['MST', 'MDT'],
  'America/Denver': ['MST', 'MDT'],
  'America/Detroit': ['EST', 'EDT'],
  'America/Edmonton': ['MST', 'MDT'],
  'America/Eirunepe': ['ACT'],
  'America/El_Salvador': ['CST', 'CDT'],
  'America/Fort_Nelson': ['MST', 'MDT'],
  'America/Fortaleza': ['BRT'],
  'America/Glace_Bay': ['AST', 'ADT'],
  'America/Goose_Bay': ['AST', 'ADT'],
  'America/Grand_Turk': ['EST', 'EDT'],
  'America/Guatemala': ['CST', 'CDT'],
  'America/Guayaquil': ['ECT'],
  'America/Guyana': ['GYT'],
  'America/Halifax': ['AST', 'ADT'],
  'America/Havana': ['HNCU', 'HECU'],
  'America/Hermosillo': ['HNPMX', 'HEPMX'],
  'America/Indiana/Indianapolis': ['EST', 'EDT'],
  'America/Indiana/Knox': ['CST', 'CDT'],
  'America/Indiana/Marengo': ['EST', 'EDT'],
  'America/Indiana/Petersburg': ['EST', 'EDT'],
  'America/Indiana/Tell_City': ['CST', 'CDT'],
  'America/Indiana/Vevay': ['EST', 'EDT'],
  'America/Indiana/Vincennes': ['EST', 'EDT'],
  'America/Indiana/Winamac': ['EST', 'EDT'],
  'America/Inuvik': ['MST', 'MDT'],
  'America/Iqaluit': ['EST', 'EDT'],
  'America/Jamaica': ['EST', 'EDT'],
  'America/Juneau': ['AKST', 'AKDT'],
  'America/Kentucky/Louisville': ['EST', 'EDT'],
  'America/Kentucky/Monticello': ['EST', 'EDT'],
  'America/La_Paz': ['BOT'],
  'America/Lima': ['PET'],
  'America/Los_Angeles': ['PST', 'PDT'],
  'America/Maceio': ['BRT'],
  'America/Managua': ['CST', 'CDT'],
  'America/Manaus': ['AMT'],
  'America/Martinique': ['AST', 'ADT'],
  'America/Matamoros': ['CST', 'CDT'],
  'America/Mazatlan': ['HNPMX', 'HEPMX'],
  'America/Menominee': ['CST', 'CDT'],
  'America/Merida': ['CST', 'CDT'],
  'America/Metlakatla': ['AKST', 'AKDT'],
  'America/Mexico_City': ['CST', 'CDT'],
  'America/Miquelon': ['HNPM', 'HEPM'],
  'America/Moncton': ['AST', 'ADT'],
  'America/Monterrey': ['CST', 'CDT'],
  'America/Montevideo': ['UYT'],
  'America/New_York': ['EST', 'EDT'],
  'America/Nipigon': ['EST', 'EDT'],
  'America/Nome': ['AKST', 'AKDT'],
  'America/Noronha': ['FNT'],
  'America/North_Dakota/Beulah': ['CST', 'CDT'],
  'America/North_Dakota/Center': ['CST', 'CDT'],
  'America/North_Dakota/New_Salem': ['CST', 'CDT'],
  'America/Nuuk': ['WGT', 'WGST'],
  'America/Ojinaga': ['MST', 'MDT'],
  'America/Panama': ['EST', 'EDT'],
  'America/Pangnirtung': ['EST', 'EDT'],
  'America/Paramaribo': ['SRT'],
  'America/Phoenix': ['MST', 'MDT'],
  'America/Port-au-Prince': ['EST', 'EDT'],
  'America/Porto_Velho': ['AMT'],
  'America/Puerto_Rico': ['AST', 'ADT'],
  'America/Punta_Arenas': ['CLT', 'CLST'],
  'America/Rainy_River': ['CST', 'CDT'],
  'America/Rankin_Inlet': ['CST', 'CDT'],
  'America/Recife': ['BRT'],
  'America/Regina': ['CST', 'CDT'],
  'America/Resolute': ['CST', 'CDT'],
  'America/Rio_Branco': ['ACT'],
  'America/Santarem': ['BRT'],
  'America/Santiago': ['CLT', 'CLST'],
  'America/Santo_Domingo': ['AST', 'ADT'],
  'America/Sao_Paulo': ['BRT'],
  'America/Scoresbysund': ['HNEG', 'HEEG'],
  'America/Sitka': ['AKST', 'AKDT'],
  'America/St_Johns': ['HNTN', 'HETN'],
  'America/Swift_Current': ['CST', 'CDT'],
  'America/Tegucigalpa': ['CST', 'CDT'],
  'America/Thule': ['AST', 'ADT'],
  'America/Thunder_Bay': ['EST', 'EDT'],
  'America/Tijuana': ['PST', 'PDT'],
  'America/Toronto': ['EST', 'EDT'],
  'America/Vancouver': ['PST', 'PDT'],
  'America/Whitehorse': ['MST', 'MDT'],
  'America/Winnipeg': ['CST', 'CDT'],
  'America/Yakutat': ['AKST', 'AKDT'],
  'America/Yellowknife': ['MST', 'MDT'],
  'Antarctica/Casey': ['CAST', 'CAST'],
  'Antarctica/Davis': ['DAVT'],
  'Antarctica/Macquarie': ['AEST', 'AEDT'],
  'Antarctica/Mawson': ['MAWT'],
  'Antarctica/Rothera': ['ART'],
  'Antarctica/Troll': ['GMT'],
  'Antarctica/Vostok': ['MSK+4'],
  'Asia/Almaty': ['ALMT'],
  'Asia/Amman': ['EET', 'EEST'],
  'Asia/Anadyr': ['ANAT'],
  'Asia/Aqtau': ['ALMT'],
  'Asia/Aqtobe': ['ALMT'],
  'Asia/Ashgabat': ['TMT'],
  'Asia/Atyrau': ['ALMT'],
  'Asia/Baghdad': ['AST'],
  'Asia/Baku': ['AZT'],
  'Asia/Bangkok': ['ICT'],
  'Asia/Barnaul': ['KRAT'],
  'Asia/Beirut': ['EET', 'EEST'],
  'Asia/Bishkek': ['KGT'],
  'Asia/Brunei': ['BNT'],
  'Asia/Chita': ['YAKT'],
  'Asia/Choibalsan': ['ULAT'],
  'Asia/Colombo': ['IST'],
  'Asia/Damascus': ['EET', 'EEST'],
  'Asia/Dhaka': ['BST'],
  'Asia/Dili': ['TLT'],
  'Asia/Dubai': ['GST'],
  'Asia/Dushanbe': ['TJT'],
  'Asia/Famagusta': ['EET', 'EEST'],
  'Asia/Gaza': ['EET', 'EEST'],
  'Asia/Hebron': ['EET', 'EEST'],
  'Asia/Ho_Chi_Minh': ['ICT'],
  'Asia/Hong_Kong': ['HKT'],
  'Asia/Hovd': ['HOVT'],
  'Asia/Irkutsk': ['IRKT'],
  'Asia/Jakarta': ['WIB'],
  'Asia/Jayapura': ['WIT'],
  'Asia/Jerusalem': ['IST', 'IDT'],
  'Asia/Kabul': ['AFT'],
  'Asia/Kamchatka': ['PETT'],
  'Asia/Karachi': ['PKT'],
  'Asia/Kathmandu': ['NPT'],
  'Asia/Khandyga': ['YAKT'],
  'Asia/Kolkata': ['IST'],
  'Asia/Krasnoyarsk': ['KRAT'],
  'Asia/Kuala_Lumpur': ['MYT'],
  'Asia/Kuching': ['MYT'],
  'Asia/Macau': ['CST'],
  'Asia/Magadan': ['MAGT'],
  'Asia/Makassar': ['WITA'],
  'Asia/Manila': ['PHST'],
  'Asia/Nicosia': ['EET', 'EEST'],
  'Asia/Novokuznetsk': ['KRAT'],
  'Asia/Novosibirsk': ['NOVT'],
  'Asia/Omsk': ['OMST'],
  'Asia/Oral': ['ALMT'],
  'Asia/Pontianak': ['WIB'],
  'Asia/Pyongyang': ['KST'],
  'Asia/Qatar': ['AST'],
  'Asia/Qostanay': ['ALMT'],
  'Asia/Qyzylorda': ['ALMT'],
  'Asia/Riyadh': ['AST'],
  'Asia/Sakhalin': ['SAKT'],
  'Asia/Samarkand': ['UZT'],
  'Asia/Seoul': ['KST'],
  'Asia/Shanghai': ['CST'],
  'Asia/Singapore': ['SGT'],
  'Asia/Srednekolymsk': ['SRET'],
  'Asia/Taipei': ['CST'],
  'Asia/Tashkent': ['UZT'],
  'Asia/Tbilisi': ['GET'],
  'Asia/Tehran': ['IRST', 'IRDT'],
  'Asia/Thimphu': ['BT'],
  'Asia/Tokyo': ['JST'],
  'Asia/Tomsk': ['OMST'],
  'Asia/Ulaanbaatar': ['ULAT'],
  'Asia/Ust-Nera': ['VLAT'],
  'Asia/Vladivostok': ['VLAT'],
  'Asia/Yakutsk': ['YAKT'],
  'Asia/Yangon': ['MMT'],
  'Asia/Yekaterinburg': ['YEKT'],
  'Asia/Yerevan': ['AMT'],
  'Atlantic/Azores': ['AZOT', 'AZOST'],
  'Atlantic/Bermuda': ['AST', 'ADT'],
  'Atlantic/Canary': ['WET', 'WEST'],
  'Atlantic/Cape_Verde': ['CVT'],
  'Atlantic/Faroe': ['WET', 'WEST'],
  'Atlantic/Madeira': ['WET', 'WEST'],
  'Atlantic/Reykjavik': ['GMT'],
  'Atlantic/South_Georgia': ['GST'],
  'Atlantic/Stanley': ['FKST'],
  'Australia/Adelaide': ['ACST', 'ACDT'],
  'Australia/Brisbane': ['AEST'],
  'Australia/Broken_Hill': ['ACST', 'ACDT'],
  'Australia/Darwin': ['ACST'],
  'Australia/Eucla': ['ACWST'],
  'Australia/Hobart': ['AEST', 'AEDT'],
  'Australia/Lindeman': ['AEST'],
  'Australia/Lord_Howe': ['LHST', 'LHDT'],
  'Australia/Melbourne': ['AEST', 'AEDT'],
  'Australia/Perth': ['AWST'],
  'Australia/Sydney': ['AEST', 'AEDT'],
  'Etc/GMT': ['GMT'],
  'Etc/UTC': ['GMT'],
  'Europe/Amsterdam': ['CET', 'CEST'],
  'Europe/Andorra': ['CET', 'CEST'],
  'Europe/Astrakhan': ['MSK'],
  'Europe/Athens': ['EET', 'EEST'],
  'Europe/Belgrade': ['CET', 'CEST'],
  'Europe/Brussels': ['CET', 'CEST'],
  'Europe/Bucharest': ['EET', 'EEST'],
  'Europe/Budapest': ['CET', 'CEST'],
  'Europe/Busingen': ['CET', 'CEST'],
  'Europe/Chisinau': ['EET', 'EEST'],
  'Europe/Copenhagen': ['CET', 'CEST'],
  'Europe/Gibraltar': ['CET', 'CEST'],
  'Europe/Helsinki': ['EET', 'EEST'],
  'Europe/Istanbul': ['TRT'],
  'Europe/Kaliningrad': ['EET', 'EEST'],
  'Europe/Kiev': ['EET', 'EEST'],
  'Europe/Kirov': ['MSK'],
  'Europe/Lisbon': ['WET', 'WEST'],
  'Europe/London': ['GMT', 'BST'],
  'Europe/Luxembourg': ['CET', 'CEST'],
  'Europe/Madrid': ['CET', 'CEST'],
  'Europe/Malta': ['CET', 'CEST'],
  'Europe/Minsk': ['MSK'],
  'Europe/Monaco': ['CET', 'CEST'],
  'Europe/Moscow': ['MSK'],
  'Europe/Oslo': ['CET', 'CEST'],
  'Europe/Paris': ['CET', 'CEST'],
  'Europe/Prague': ['CET', 'CEST'],
  'Europe/Riga': ['EET', 'EEST'],
  'Europe/Rome': ['CET', 'CEST'],
  'Europe/Samara': ['SAMT'],
  'Europe/Saratov': ['SAMT'],
  'Europe/Sofia': ['EET', 'EEST'],
  'Europe/Stockholm': ['CET', 'CEST'],
  'Europe/Tallinn': ['EET', 'EEST'],
  'Europe/Tirane': ['CET', 'CEST'],
  'Europe/Ulyanovsk': ['MSK'],
  'Europe/Uzhgorod': ['EET', 'EEST'],
  'Europe/Vienna': ['CET', 'CEST'],
  'Europe/Vilnius': ['EET', 'EEST'],
  'Europe/Volgograd': ['MSK'],
  'Europe/Warsaw': ['CET', 'CEST'],
  'Europe/Zaporozhye': ['EET', 'EEST'],
  'Europe/Zurich': ['CET', 'CEST'],
  'Indian/Chagos': ['IOT'],
  'Indian/Christmas': ['CXT'],
  'Indian/Cocos': ['CCT'],
  'Indian/Kerguelen': ['TFT'],
  'Indian/Mahe': ['SCT'],
  'Indian/Maldives': ['MVT'],
  'Indian/Mauritius': ['MUT'],
  'Indian/Reunion': ['RET'],
  'Pacific/Apia': ['WST', 'WST'],
  'Pacific/Auckland': ['NZST', 'NZDT'],
  'Pacific/Bougainville': ['PGT'],
  'Pacific/Chatham': ['CHAST', 'CHADT'],
  'Pacific/Chuuk': ['CHUT'],
  'Pacific/Easter': ['EAST', 'EASST'],
  'Pacific/Efate': ['VUT'],
  'Pacific/Fakaofo': ['TKT'],
  'Pacific/Fiji': ['FJT', 'FJT'],
  'Pacific/Funafuti': ['TVT'],
  'Pacific/Galapagos': ['COT'],
  'Pacific/Gambier': ['GAMT'],
  'Pacific/Guadalcanal': ['SBT'],
  'Pacific/Guam': ['ChST'],
  'Pacific/Honolulu': ['HAST', 'HADT'],
  'Pacific/Kanton': ['PHOT'],
  'Pacific/Kiritimati': ['LINT'],
  'Pacific/Kosrae': ['KOST'],
  'Pacific/Kwajalein': ['MHT'],
  'Pacific/Majuro': ['MHT'],
  'Pacific/Marquesas': ['MART'],
  'Pacific/Nauru': ['NRT'],
  'Pacific/Niue': ['NUT'],
  'Pacific/Norfolk': ['NFT', 'NFDT'],
  'Pacific/Noumea': ['NCT'],
  'Pacific/Pago_Pago': ['SST'],
  'Pacific/Palau': ['PWT'],
  'Pacific/Pitcairn': ['PST'],
  'Pacific/Pohnpei': ['PONT'],
  'Pacific/Port_Moresby': ['PGT'],
  'Pacific/Rarotonga': ['CKT'],
  'Pacific/Tahiti': ['TAHT'],
  'Pacific/Tarawa': ['GILT'],
  'Pacific/Tongatapu': ['TOT'],
  'Pacific/Wake': ['WAKT'],
  'Pacific/Wallis': ['WFT']
}