module.exports = {
  0: [
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Bamako',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Conakry',
    'Africa/Dakar',
    'Africa/Freetown',
    'Africa/Lome',
    'Africa/Monrovia',
    'Africa/Nouakchott',
    'Africa/Ouagadougou',
    'Africa/Sao_Tome',
    'Africa/Timbuktu',
    'America/Danmarkshavn',
    'Atlantic/Reykjavik',
    'Atlantic/St_Helena',
    'Etc/GMT',
    'Etc/GMT+0',
    'Etc/GMT-0',
    'Etc/GMT0',
    'Etc/Greenwich',
    'Etc/Utc',
    'Etc/Universal',
    'Etc/Zulu'
  ],
  1: [
    'Africa/Algiers',
    'Africa/Bangui',
    'Africa/Brazzaville',
    'Africa/Douala',
    'Africa/Lagos',
    'Africa/Libreville',
    'Africa/Malabo',
    'Africa/Ndjamena',
    'Africa/Niamey',
    'Africa/Porto-novo',
    'Africa/Tunis'
  ],
  2: [
    'Africa/Blantyre',
    'Africa/Bujumbura',
    'Africa/Cairo',
    'Africa/Khartoum',
    'Africa/Kigali',
    'Africa/Tripoli',
    'Europe/Kaliningrad'
  ],
  3: [
    'Africa/Addis_Ababa',
    'Africa/Asmara',
    'Africa/Asmera',
    'Africa/Dar_Es_Salaam',
    'Africa/Djibouti',
    'Africa/Juba',
    'Africa/Kampala',
    'Africa/Mogadishu',
    'Africa/Nairobi',
    'Asia/Aden',
    'Asia/Baghdad',
    'Asia/Bahrain',
    'Asia/Istanbul',
    'Asia/Kuwait',
    'Asia/Qatar',
    'Asia/Riyadh',
    'Europe/Istanbul',
    'Europe/Kirov',
    'Europe/Minsk',
    'Europe/Moscow',
    'Europe/Simferopol',
    'Indian/Comoro',
    'Indian/Mayotte'
  ],
  4: [
    'Asia/Dubai',
    'Asia/Muscat',
    'Asia/Tbilisi',
    'Asia/Yerevan',
    'Europe/Astrakhan',
    'Europe/Samara',
    'Europe/Saratov',
    'Europe/Ulyanovsk',
    'Europe/Volgograd',
    'Asia/Volgograd',
    'Indian/Mahe',
    'Indian/Mauritius'
  ],
  4.5: ['Asia/Kabul'],
  5: [
    'Asia/Aqtau',
    'Asia/Aqtobe',
    'Asia/Ashgabat',
    'Asia/Ashkhabad',
    'Asia/Atyrau',
    'Asia/Baku',
    'Asia/Dushanbe',
    'Asia/Karachi',
    'Asia/Oral',
    'Asia/Samarkand',
    'Asia/Tashkent',
    'Asia/Yekaterinburg',
    'Indian/Maldives'
  ],
  5.5: ['Asia/Calcutta', 'Asia/Colombo', 'Asia/Kolkata'],
  5.75: ['Asia/Kathmandu', 'Asia/Katmandu'],
  6: [
    'Asia/Almaty',
    'Asia/Bishkek',
    'Asia/Dacca',
    'Asia/Dhaka',
    'Asia/Kashgar',
    'Asia/Omsk',
    'Asia/Qyzylorda',
    'Asia/Qostanay',
    'Asia/Thimbu',
    'Asia/Thimphu',
    'Asia/Urumqi',
    'Indian/Chagos'
  ],
  6.5: ['Asia/Rangoon', 'Asia/Yangon', 'Indian/Cocos'],
  7: [
    'Asia/Bangkok',
    'Asia/Barnaul',
    'Asia/Ho_Chi_Minh',
    'Asia/Hovd',
    'Asia/Krasnoyarsk',
    'Asia/Novokuznetsk',
    'Asia/Novosibirsk',
    'Asia/Phnom_Penh',
    'Asia/Pontianak',
    'Asia/Saigon',
    'Asia/Tomsk',
    'Asia/Vientiane'
  ],
  8: [
    'Asia/Brunei',
    'Asia/Choibalsan',
    'Asia/Chongqing',
    'Asia/Chungking',
    'Asia/Harbin',
    'Asia/Hong_Kong',
    'Asia/Irkutsk',
    'Asia/Kuching',
    'Asia/Macao',
    'Asia/Macau',
    'Asia/Manila',
    'Asia/Shanghai',
    'Asia/Taipei',
    'Asia/Ujung_Pandang',
    'Asia/Ulaanbaatar'
  ],
  9: ['Asia/Chita', 'Asia/Khandyga', 'Asia/Pyongyang', 'Asia/Seoul', 'Asia/Tokyo', 'Pacific/Palau'],
  10: [
    'Asia/Ust-nera',
    'Asia/Vladivostok',
    'Asia/Yakutsk',
    'Pacific/Chuuk',
    'Pacific/Guam',
    'Pacific/Port_Moresby',
    'Pacific/Saipan',
    'Pacific/Truk',
    'Pacific/Yap'
  ],
  11: [
    'Asia/Magadan',
    'Asia/Sakhalin',
    'Pacific/Efate',
    'Pacific/Guadalcanal',
    'Pacific/Kosrae',
    'Pacific/Noumea',
    'Pacific/Pohnpei',
    'Pacific/Ponape'
  ],
  12: [
    'Asia/Anadyr',
    'Asia/Kamchatka',
    'Asia/Srednekolymsk',
    'Pacific/Funafuti',
    'Pacific/Kwajalein',
    'Pacific/Majuro',
    'Pacific/Nauru',
    'Pacific/Tarawa',
    'Pacific/Wake',
    'Pacific/Wallis'
  ],
  13: ['Pacific/Enderbury', 'Pacific/Fakaofo'],
  14: ['Pacific/Kiritimati'],

  // eastern hemisphere
  '-11': ['Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago', 'Pacific/Samoa'],
  '-10': ['Pacific/Honolulu', 'Pacific/Johnston', 'Pacific/Rarotonga', 'Pacific/Tahiti'],
  '-9.5': ['Pacific/Marquesas'],
  '-9': ['Pacific/Gambier'],
  '-8': ['Pacific/Pitcairn'],
  '-7': [
    'America/Creston',
    'America/Dawson_Creek',
    'America/Fort_Nelson',
    'America/Hermosillo',
    'America/Phoenix'
  ],
  '-6': [
    'America/Belize',
    'America/Costa_Rica',
    'America/El_Salvador',
    'America/Guatemala',
    'America/Managua',
    'America/Regina',
    'America/Swift_Current',
    'America/Tegucigalpa',
    'Canada/East-saskatchewan',
    'Canada/Saskatchewan',
    'Pacific/Galapagos'
  ],
  '-5': [
    'America/Atikokan',
    'America/Bogota',
    'America/Cancun',
    'America/Cayman',
    'America/Coral_Harbour',
    'America/Eirunepe',
    'America/Guayaquil',
    'America/Jamaica',
    'America/Panama',
    'America/Porto_Acre'
  ],
  '-4': [
    'America/Anguilla',
    'America/Antigua',
    'America/Aruba',
    'America/Barbados',
    'America/Blanc-sablon',
    'America/Boa_Vista',
    'America/Caracas',
    'America/Curacao',
    'America/Dominica',
    'America/Grenada',
    'America/Guadeloupe',
    'America/Guyana',
    'America/Kralendijk',
    'America/Lower_Princes',
    'America/Marigot',
    'America/Martinique',
    'America/Montserrat',
    'America/Port_Of_Spain',
    'America/Porto_Velho',
    'America/Puerto_Rico',
    'America/Santo_Domingo',
    'America/St_Barthelemy',
    'America/St_Kitts',
    'America/St_Lucia',
    'America/St_Thomas',
    'America/St_Vincent',
    'America/Tortola',
    'America/Virgin'
  ],
  '-3': [
    'America/Araguaina',
    'America/Bahia',
    'America/Belem',
    'America/Catamarca',
    'America/Cayenne',
    'America/Jujuy',
    'America/Maceio',
    'America/Mendoza',
    'America/Paramaribo',
    'America/Recife',
    'America/Rosario',
    'America/Santarem'
  ],
  '-2': ['America/Noronha', 'Atlantic/South_Georgia'],
  '-1': ['Atlantic/Cape_Verde']
}
