import test from 'tape'
import spacetime from 'spacetime/temporal'

const options = { skip: !globalThis.Temporal }

test('Temporal entry: public parsing and formatting', options, (t) => {
  const s = spacetime('March 1 2012 3:22pm', 'America/New_York')
  t.equal(s.format('{day-short} {month} {date-ordinal}, {time}'), 'Thu March 1st, 3:22pm')
  t.equal(s.unixFmt('yyyy-MM-dd HH:mm'), '2012-03-01 15:22')
  t.equal(s.goto('America/Los_Angeles').time(), '12:22pm')
  t.equal(s.goto('America/Los_Angeles').epoch, s.epoch, 'goto keeps instant')
  t.equal(s.timezone('America/Los_Angeles').time(), '3:22pm', 'timezone keeps clock')
  t.equal(s.month(), 2, 'zero-based month')
  t.equal(s.date(), 1)
  t.equal(spacetime([2017, 5, 2], 'UTC').format('iso-short'), '2017-06-02')
  t.equal(spacetime({ year: 2024, month: 1, date: 29 }, 'UTC').format('iso-short'), '2024-02-29')
  t.equal(spacetime('25-feb-2015', 'UTC').format('iso-short'), '2015-02-25')
  t.equal(spacetime('02/03/2024', 'UTC', { british: true }).format('iso-short'), '2024-03-02')
  t.equal(spacetime('March 1', 'UTC', { today: { year: 2020 } }).year(), 2020)
  t.equal(spacetime('2024-03-01T12:30:00+05:45').offset(), 345)
  t.equal(spacetime(0, 'UTC').epoch, 0)
  t.equal(spacetime({ epoch: 0, tz: 'UTC' }).epoch, 0)
  t.equal(spacetime.fromUnixSeconds(123, 'UTC').epoch, 123000)
  t.equal(spacetime(new Date(123000), 'UTC').epoch, 123000)
  t.end()
})

test('Temporal entry: calendar and clock arithmetic', options, (t) => {
  const s = spacetime('2024-01-31T12:30:00', 'UTC')
  t.equal(s.add(1, 'month').format('iso-short'), '2024-02-29', 'clamp leap month')
  t.equal(s.add(1, 'month').add(1, 'year').format('iso-short'), '2025-02-28')
  t.equal(s.add(1.5, 'hour').time(), '2:00pm')
  t.equal(s.month(1).date(), 29)
  t.equal(s.hour(9).hour(), 9)
  t.equal(s.hour(), 12, 'setter is immutable')
  t.equal(s.date(), 31, 'arithmetic is immutable')
  t.equal(s.endOf('month').iso(), '2024-01-31T23:59:59.999Z')
  t.equal(s.startOf('year').iso(), '2024-01-01T00:00:00.000Z')
  t.equal(s.startOf('week').format('iso-short'), '2024-01-29')
  t.equal(s.clone().weekStart(0).startOf('week').format('iso-short'), '2024-01-28')
  t.equal(s.diff(s.add(3, 'month'), 'months'), 3)
  t.equal(s.diff(s.subtract(2, 'hour'), 'hours'), -2)
  t.ok(s.isBefore(s.add(1, 'day')))
  t.ok(s.isAfter(s.subtract(1, 'day')))
  t.ok(s.isSame(s.hour(3), 'day'))
  t.ok(s.isEqual(s.clone()))
  t.equal(s.dayOfYear(), 31)
  t.equal(s.daysInMonth(), 31)
  t.ok(s.leapYear())
  t.end()
})

test('Temporal entry: native DST resolution', options, (t) => {
  const s = spacetime('2024-03-09T12:00:00', 'America/New_York')
  const tomorrow = s.add(1, 'day')
  t.equal(tomorrow.hour(), 12, 'calendar day preserves local hour')
  t.equal(tomorrow.epoch - s.epoch, 23 * 3600000)
  t.equal(s.add(24, 'hour').hour(), 13, 'hours measure elapsed time')
  t.equal(s.diff(tomorrow, 'day'), 1)
  t.equal(s.diff(tomorrow, 'hour'), 23)
  t.equal(spacetime('2024-03-10T02:30:00', s.tz).time(), '3:30am', 'gap moves forward')
  const first = spacetime('2024-11-03T01:30:00-04:00[America/New_York]')
  const second = spacetime('2024-11-03T01:30:00-05:00[America/New_York]')
  t.equal(second.epoch - first.epoch, 3600000, 'offset selects repeated hour')
  t.equal(second.startOf('hour').offset(), -300, 'boundary preserves repeated hour')
  t.equal(second.endOf('day').epoch - second.startOf('day').epoch + 1, 25 * 3600000)
  t.equal(spacetime('2018-11-04', 'America/Sao_Paulo').startOf('day').hour(), 1, 'skipped midnight')
  t.end()
})

test('Temporal entry: interop and invalid dates', options, (t) => {
  const T = globalThis.Temporal
  const zdt = T.ZonedDateTime.from('2024-02-29T10:20:30+01:00[Europe/Paris]')
  const s = spacetime(zdt)
  t.ok(s.toTemporal().equals(zdt))
  t.equal(spacetime(zdt.toInstant(), 'UTC').epoch, s.epoch)
  t.equal(spacetime(T.PlainDate.from('2024-02-29'), 'UTC').format('iso-short'), '2024-02-29')
  t.equal(s.toNativeDate().getTime(), s.epoch)
  for (const input of ['not a date', '2023-02-29', '2024-01-01T25:00:00', NaN, new Date(NaN)]) {
    const invalid = spacetime(input, 'UTC')
    t.notOk(invalid.isValid(), String(input))
    t.equal(invalid.format('iso'), '')
    t.notOk(invalid.clone().isValid(), 'invalid stays invalid')
    t.notOk(invalid.add(1, 'day').isValid(), 'arithmetic stays invalid')
  }
  t.end()
})
