export default `Africa
	Abidjan,0,GMT
	Algiers,1,CET|CEST
	Bissau,0,GMT
	Cairo,2,EET|EEST
	Casablanca,0,WET|WEST,saha
	Ceuta,1,CET|CEST,eu2
	El_Aaiun,0,WET|WEST,saha
	Johannesburg,2,SAST,s
	Juba,3,CAT
	Khartoum,2,CAT
	Lagos,1,WAT
	Maputo,2,CAT,s
	Monrovia,0,GMT
	Nairobi,3,EAT
	Ndjamena,1,WAT
	Sao_Tome,0,GMT
	Tripoli,2,EET|EEST
	Tunis,1,CET|CEST
	Windhoek,1,CAT,s
America
	Adak,-10,HST|HDT,usa
	Anchorage,-9,AKST|AKDT,usa
	Araguaina,-3,BRT
	Argentina/Buenos_Aires,-3,ART,s
	Asuncion,-4,PYT|PYST,par,s
	Bahia,-3,BRT
	Bahia_Banderas,-6,CST|CDT,mex
	Barbados,-4,AST|ADT
	Belem,-3,BRT
	Belize,-6,CST|CDT
	Boa_Vista,-4,AMT
	Bogota,-5,COT
	Boise,-7,MST|MDT,usa
	Cambridge_Bay,-7,MST|MDT,usa
	Campo_Grande,-4,AMT,s
	Cancun,-5,EST|EDT
	Caracas,-4,VET
	Cayenne,-3,GFT
	Chicago,-6,CST|CDT,usa
	Chihuahua,-7,HNPMX|HEPMX,mex
	Costa_Rica,-6,CST|CDT
	Cuiaba,-4,AMT,s
	Danmarkshavn,0,GMT
	Dawson,-7,MST|MDT
	Dawson_Creek,-7,MST|MDT
	Denver,-7,MST|MDT,usa
	Detroit,-5,EST|EDT,usa
	Edmonton,-7,MST|MDT,usa
	Eirunepe,-5,ACT
	El_Salvador,-6,CST|CDT
	Fort_Nelson,-7,MST|MDT
	Fortaleza,-3,BRT,s
	Glace_Bay,-4,AST|ADT,usa
	Goose_Bay,-4,AST|ADT,usa
	Grand_Turk,-5,EST|EDT,usa
	Guatemala,-6,CST|CDT
	Guayaquil,-5,ECT
	Guyana,-4,GYT
	Halifax,-4,AST|ADT,usa
	Havana,-5,HNCU|HECU,cuba
	Hermosillo,-7,HNPMX|HEPMX
	Indiana/Knox,-6,CST|CDT,usa
	Indiana/Marengo,-5,EST|EDT,usa
	Indiana/Petersburg,-5,EST|EDT,usa
	Indiana/Tell_City,-6,CST|CDT,usa
	Indiana/Vevay,-5,EST|EDT,usa
	Indiana/Vincennes,-5,EST|EDT,usa
	Indiana/Winamac,-5,EST|EDT,usa
	Inuvik,-7,MST|MDT,usa
	Iqaluit,-5,EST|EDT,usa
	Jamaica,-5,EST|EDT
	Juneau,-9,AKST|AKDT,usa
	Kentucky/Monticello,-5,EST|EDT,usa
	La_Paz,-4,BOT,s
	Lima,-5,PET,s
	Los_Angeles,-8,PST|PDT,usa
	Maceio,-3,BRT
	Managua,-6,CST|CDT
	Manaus,-4,AMT,s
	Martinique,-4,AST|ADT
	Matamoros,-6,CST|CDT,usa
	Mazatlan,-7,HNPMX|HEPMX,mex
	Menominee,-6,CST|CDT,usa
	Merida,-6,CST|CDT,mex
	Metlakatla,-9,AKST|AKDT,usa
	Mexico_City,-6,CST|CDT,mex
	Miquelon,-3,HNPM|HEPM,usa
	Moncton,-4,AST|ADT,usa
	Monterrey,-6,CST|CDT,mex
	Montevideo,-3,UYT,s
	New_York,-5,EST|EDT,usa
	Nipigon,-5,EST|EDT,usa
	Nome,-9,AKST|AKDT,usa
	Noronha,-2,FNT
	North_Dakota/Beulah,-6,CST|CDT,usa
	North_Dakota/Center,-6,CST|CDT,usa
	North_Dakota/New_Salem,-6,CST|CDT,usa
	Nuuk,-3,WGT|WGST,green
	Ojinaga,-7,MST|MDT,usa
	Panama,-5,EST|EDT
	Pangnirtung,-5,EST|EDT,usa
	Paramaribo,-3,SRT
	Phoenix,-7,MST|MDT
	Port-au-prince,-5,EST|EDT,usa
	Porto_Velho,-4,AMT
	Puerto_Rico,-4,AST|ADT
	Punta_Arenas,-3,CLT|CLST,s
	Rainy_River,-6,CST|CDT,usa
	Rankin_Inlet,-6,CST|CDT,usa
	Recife,-3,BRT
	Regina,-6,CST|CDT
	Resolute,-6,CST|CDT,usa
	Rio_Branco,-5,ACT,s
	Santarem,-3,BRT
	Santiago,-4,CLT|CLST,chile,s
	Santo_Domingo,-4,AST|ADT
	Sao_Paulo,-3,BRT,s
	Scoresbysund,-1,HNEG|HEEG,eu0
	Sitka,-9,AKST|AKDT,usa
	St_Johns,-3.5,HNTN|HETN,usa
	Swift_Current,-6,CST|CDT
	Tegucigalpa,-6,CST|CDT
	Thule,-4,AST|ADT,usa
	Thunder_Bay,-5,EST|EDT,usa
	Tijuana,-8,PST|PDT,usa
	Toronto,-5,EST|EDT,usa
	Vancouver,-8,PST|PDT,usa
	Whitehorse,-7,MST|MDT
	Winnipeg,-6,CST|CDT,usa
	Yakutat,-9,AKST|AKDT,usa
	Yellowknife,-7,MST|MDT,usa
Antarctica
	Casey,8,CAST|CAST,ant,s
	Davis,7,DAVT,s
	Macquarie,11,AEST|AEDT,aus,s
	Mawson,5,MAWT,s
	Rothera,-3,ART,s
	Troll,2,GMT,troll,s
	Vostok,6,MSK+4,s
Asia
	Almaty,6,ALMT
	Amman,2,EET|EEST,jord
	Anadyr,12,ANAT
	Aqtau,5,ALMT
	Aqtobe,5,ALMT
	Ashgabat,5,TMT
	Atyrau,5,ALMT
	Baghdad,3,AST
	Baku,4,AZT
	Bangkok,7,ICT
	Barnaul,7,KRAT
	Beirut,2,EET|EEST,leb
	Bishkek,6,KGT
	Brunei,8,BNT
	Chita,9,YAKT
	Choibalsan,8,ULAT
	Colombo,5.5,IST
	Damascus,2,EET|EEST,syr
	Dhaka,6,BST
	Dili,9,TLT,s
	Dubai,4,GST
	Dushanbe,5,TJT
	Famagusta,2,EET|EEST,eu3
	Gaza,2,EET|EEST,pal
	Hebron,2,EET|EEST,pal
	Ho_Chi_Minh,7,ICT
	Hong_Kong,8,HKT
	Hovd,7,HOVT
	Irkutsk,8,IRKT
	Jakarta,7,WIB,s
	Jayapura,9,WIT,s
	Jerusalem,2,IST|IDT,isr
	Kabul,4.5,AFT
	Kamchatka,12,PETT
	Karachi,5,PKT
	Kathmandu,5.75,NPT
	Khandyga,9,YAKT
	Kolkata,5.5,IST
	Krasnoyarsk,7,KRAT
	Kuala_Lumpur,8,MYT,s
	Kuching,8,MYT
	Macau,8,CST
	Magadan,11,MAGT
	Makassar,8,WITA,s
	Manila,8,PHST
	Nicosia,2,EET|EEST,eu3
	Novokuznetsk,7,KRAT
	Novosibirsk,7,NOVT
	Omsk,6,OMST
	Oral,5,ALMT
	Pontianak,7,WIB
	Pyongyang,9,KST
	Qatar,3,AST
	Qostanay,6,ALMT
	Qyzylorda,6,ALMT
	Riyadh,3,AST
	Sakhalin,11,SAKT
	Samarkand,5,UZT
	Seoul,9,KST
	Shanghai,8,CST
	Singapore,8,SGT,s
	Srednekolymsk,12,SRET
	Taipei,8,CST
	Tashkent,5,UZT
	Tbilisi,4,GET
	Tehran,3.5,IRST|IRDT,iran
	Thimphu,6,BT
	Tokyo,9,JST
	Tomsk,7,OMST
	Ulaanbaatar,8,ULAT
	Ust-nera,10,VLAT
	Vladivostok,10,VLAT
	Yakutsk,10,YAKT
	Yangon,6.5,MMT
	Yekaterinburg,5,YEKT
	Yerevan,4,AMT
Atlantic
	Azores,-1,AZOT|AZOST,eu0
	Bermuda,-4,AST|ADT,usa
	Canary,0,WET|WEST,eu1
	Cape_Verde,-1,CVT
	Faroe,0,WET|WEST,eu1
	Madeira,0,WET|WEST,eu1
	Reykjavik,0,GMT
	South_Georgia,-2,GST
	Stanley,-3,FKST,s
Australia
	Adelaide,9.5,ACST|ACDT,aus,s
	Brisbane,10,AEST,s
	Broken_Hill,9.5,ACST|ACDT,aus,s
	Darwin,9.5,ACST,s
	Eucla,8.75,ACWST,s
	Hobart,10,AEST|AEDT,aus,s
	Lindeman,10,AEST,s
	Lord_Howe,10.5,LHST|LHDT,lhow,s
	Melbourne,10,AEST|AEDT,aus,s
	Perth,8,AWST,s
	Sydney,10,AEST|AEDT,aus,s
Etc
	GMT,0,GMT
	Utc,0,UTC
Europe
	Amsterdam,1,CET|CEST,eu2
	Andorra,1,CET|CEST,eu2
	Astrakhan,4,MSK
	Athens,2,EET|EEST,eu3
	Belgrade,1,CET|CEST,eu2
	Brussels,1,CET|CEST,eu2
	Bucharest,2,EET|EEST,eu3
	Budapest,1,CET|CEST,eu2
	Busingen,1,CET|CEST,eu2
	Chisinau,2,EET|EEST,eu2
	Copenhagen,1,CET|CEST,eu2
	Dublin,0,GMT|IST,eu1
	Gibraltar,1,CET|CEST,eu2
	Helsinki,2,EET|EEST,eu3
	Istanbul,3,TRT
	Kaliningrad,2,EET|EEST
	Kiev,2,EET|EEST,eu3
	Kirov,3,MSK
	Lisbon,0,WET|WEST,eu1
	London,0,GMT|BST,eu1
	Luxembourg,1,CET|CEST,eu2
	Madrid,1,CET|CEST,eu2
	Malta,1,CET|CEST,eu2
	Minsk,3,MSK
	Monaco,1,CET|CEST,eu2
	Moscow,3,MSK
	Oslo,1,CET|CEST,eu2
	Paris,1,CET|CEST,eu2
	Prague,1,CET|CEST,eu2
	Riga,2,EET|EEST,eu3
	Rome,1,CET|CEST,eu2
	Samara,4,SAMT
	Saratov,4,SAMT
	Sofia,2,EET|EEST,eu3
	Stockholm,1,CET|CEST,eu2
	Tallinn,2,EET|EEST,eu3
	Tirane,1,CET|CEST,eu2
	Ulyanovsk,4,MSK
	Uzhgorod,2,EET|EEST,eu3
	Vienna,1,CET|CEST,eu2
	Vilnius,2,EET|EEST,eu3
	Volgograd,4,MSK
	Warsaw,1,CET|CEST,eu2
	Zaporozhye,2,EET|EEST,eu3
	Zurich,1,CET|CEST,eu2
Indian
	Chagos,6,IOT
	Christmas,7,CXT,s
	Cocos,6.5,CCT
	Kerguelen,5,TFT,s
	Mahe,4,SCT
	Maldives,5,MVT
	Mauritius,4,MUT
	Reunion,4,RET,s
Pacific
	Apia,13,WST|WST,s
	Auckland,12,NZST|NZDT,nz,s
	Bougainville,11,PGT,s
	Chatham,12.75,CHAST|CHADT,chat,s
	Chuuk,10,CHUT
	Easter,-6,EAST|EASST,east,s
	Efate,11,VUT
	Fakaofo,13,TKT
	Fiji,12,FJT|FJT,fiji,s
	Funafuti,12,TVT
	Galapagos,-6,COT
	Gambier,-9,GAMT
	Guadalcanal,11,SBT
	Guam,10,ChST
	Honolulu,-10,HAST|HADT
	Kanton,13,PHOT
	Kiritimati,14,LINT
	Kosrae,11,KOST
	Kwajalein,12,MHT
	Majuro,12,MHT
	Marquesas,-9.5,MART
	Nauru,12,NRT
	Niue,-11,NUT
	Norfolk,10.5,NFT|NFDT,aus
	Noumea,11,NCT
	Pago_Pago,-11,SST
	Palau,9,PWT
	Pitcairn,-8,PST
	Pohnpei,11,PONT
	Port_Moresby,10,PGT,s
	Rarotonga,-10,CKT
	Tahiti,-10,TAHT
	Tarawa,12,GILT
	Tongatapu,13,TOT,s
	Wake,12,WAKT
	Wallis,12,WFT
`