name: Build and test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.node-version }}-
            ${{ runner.os }}-npm-

      - name: npm install, build, and test
        run: |
          npm ci
          npm i eslint ts-node typescript
          npm run lint
          npm run pack
          npm run build
          npm run testb
          # npm run test:types
        env:
          CI: true
